name = "Ronnys Server"
author = "Ronny Pfannschmidt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff15004b04edfbd77702f07e030b028b3c5f90e6e7ac77c133c3e778bb6d4f41"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
datapack-folder = "datapacks"
